name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest --cov=app --cov-report=xml
      working-directory: ${{ github.workspace }}

    - name: SonarQube scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectBaseDir=${{ github.workspace }}
          -Dsonar.host.url=http://localhost:9000
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

